### PR TITLE
Update v2 branch; Fixed File size issue

### PR DESCRIPTION
**Pull request by BharathKSunil**
## Changes:
As part of this implementation these enhancements were performed:
- Upgraded Libraries in `file-logger` module to cater to the filesize not being restricted issue.
- Optimised `FileLoggingSetup` to use Builder Pattern.
- Moved `FileLoggingSetup.Mode` as independent class `FileLoggingMode`
- Added new Modes [Weekly Rollovers and Monthly Rollovers] as library enhancemnts.
- Updated `Demo` module to check if file creation is working.

## Additional Work to be done:
- Update the Demo and add fragments to showcase all features of the library.
- Brainstorm on enhancing the current changes and on adding more rollover policies
- Update README.md

### CODE REVIEW

**Review by nsaranhya — APPROVED** [review]

**Review by balramp — APPROVED** [review]

**Comment by balramp** [comment]
@BharathKSunil  Give some time to Golden team to review this PR .

**Comment by BharathKSunil** [comment]
@balramp ok we will wait for the Golden Team.
In the meantime I will cut out a new branch from `update_v2` to enhance the library as a personal committment.

**Comment by cbauer10** [comment]
Has anyone on the residential Golden side reviewed this?  We don’t use it on Commercial, so I want to make sure someone is having a look.

Christopher Bauer
Lead Software Engineer - Mobile Apps

Analytical | Responsibility | Focus | Strategic | Significance

Allegion
500 Golden Ridge Rd. #160
Golden, CO 80401
Office: 303-640-2715
Mobile: 303-949-6637
Email: Christopher.Bauer@allegion.com<mailto:Christopher.Bauer@allegion.com>
www.allegion.com<http://www.allegion.com>

[cid:ABFED5D7-EC9F-4F85-A802-ABA859CED9A1@wp.comcast.net]


The information contained in this message is privileged and intended only for the recipients named. If the reader is not a representative of the intended recipient, any review, dissemination or copying of this message of the information it contains is prohibited. If you have received this message in error, please notify the sender and delete the original email and any attachments.

On Apr 30, 2019, at 4:21 AM, Bharath Kumar S <notifications@github.com<mailto:notifications@github.com>> wrote:


@balramp<https://github.com/balramp> ok we will wait for the Golden Team.
In the meantime I will cut out a new branch from update_v2 to enhance the library as a personal committment.

**Comment by BharathKSunil** [comment]
@cbauer10 We are using it in commertial as well just for internal purposes. Since these enhancements were made in the v2 branch the original author declined to accept these as he no longer wants to support v2. For timebeing can we continue using v2 and ask someone in the Golden team to review this.
Also can you add @navinilavarasan and @arunseshagiri to this org?

**Pull request merged**
